In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [ ]:
df=pd.read_csv("/content/slr.csv")

In [ ]:
df.head()


SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [ ]:
x=df.iloc[:,0].values.reshape(-1,1)
y=df.iloc[:,1].values

In [ ]:
x.shape

(84, 1)

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
x_train, x_test , y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=0)

In [ ]:
Lin=LinearRegression()

In [ ]:
Lin.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=Lin.predict(x_test)

In [ ]:
y_pred


array([3.19143271, 3.35562407, 3.07684082, 3.24787349, 3.01013808,
       3.37956865, 3.17603977, 3.12472997, 3.22221859, 3.23077023,
       3.46850564, 3.09394409, 3.32996917, 3.62072471, 3.16748814,
       3.2803697 , 3.61217308])

In [ ]:
y_test

array([3.28, 3.37, 3.39, 3.41, 3.2 , 3.44, 2.54, 3.47, 3.28, 3.01, 3.58,
       3.08, 3.52, 3.65, 3.17, 3.28, 3.62])

In [ ]:
y_pred - y_test

array([-8.85672886e-02, -1.43759255e-02, -3.13159177e-01, -1.62126508e-01,
       -1.89861919e-01, -6.04313517e-02,  6.36039771e-01, -3.45270030e-01,
       -5.77814080e-02,  2.20770225e-01, -1.11494363e-01,  1.39440895e-02,
       -1.90030826e-01, -2.92752871e-02, -2.51186241e-03,  3.69699750e-04,
       -7.82692057e-03])

In [ ]:
Lin.predict([[1680]]) #predict values 

array([3.03921364])

In [ ]:
from sklearn import metrics

In [ ]:
metrics.mean_absolute_error(y_test,y_pred)

0.14375509721383473

In [ ]:
metrics.mean_squared_error(y_test,y_pred)

0.04691776855623536